### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by amiroof** [shiningw/ncdownloader#130]
Im getting an internal error when clicking on NCDownloader icon. Its a fresh vps with ubuntu 22 and apache. I have tried rebuilding the vps and installing everything fresh but cant seem to shake this error off.

Webpage error:

Internal Server Error

The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.
Technical details

    Remote Address: 2a0d:2787:1b:3dd::a
    Request ID: BtEv10gK4LJcxm4rVjVJ
    Type: Symfony\Component\Process\Exception\ProcessSignaledException
    Code: 0
    Message: The process has been signaled with signal "11".
    File: /var/www/nextcloud/3rdparty/symfony/process/Process.php
    Line: 441

Trace

#0 /var/www/nextcloud/3rdparty/symfony/process/Process.php(251): Symfony\Component\Process\Process->wait()
#1 /var/www/nextcloud/3rdparty/symfony/process/Process.php(268): Symfony\Component\Process\Process->run()
#2 /var/www/nextcloud/apps/ncdownloader/lib/Aria2/Aria2.php(375): Symfony\Component\Process\Process->mustRun()
#3 /var/www/nextcloud/apps/ncdownloader/lib/Controller/MainController.php(94): OCA\NCDownloader\Aria2\Aria2->start()
#4 /var/www/nextcloud/apps/ncdownloader/lib/Controller/MainController.php(59): OCA\NCDownloader\Controller\MainController->buildParams()
#5 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(230): OCA\NCDownloader\Controller\MainController->Index()
#6 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(137): OC\AppFramework\Http\Dispatcher->executeController()
#7 /var/www/nextcloud/lib/private/AppFramework/App.php(183): OC\AppFramework\Http\Dispatcher->dispatch()
#8 /var/www/nextcloud/lib/private/Route/Router.php(315): OC\AppFramework\App::main()
#9 /var/www/nextcloud/lib/base.php(1058): OC\Route\Router->match()
#10 /var/www/nextcloud/index.php(36): OC::handleRequest()
#11 {main}

Nextcloud log:

{"reqId":"BtEv10gK4LJcxm4rVjVJ","level":3,"time":"2023-06-08T17:41:32+00:00","remoteAddr":"2a0d:2787:1b:3dd::a","user":"Amir","app":"index","method":"GET","url":"/index.php/apps/ncdownloader/","message":"The process has been signaled with signal \"11\".","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0","version":"26.0.2.1","exception":{"Exception":"Symfony\\Component\\Process\\Exception\\ProcessSignaledException","Message":"The process has been signaled with signal \"11\".","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/symfony/process/Process.php","line":251,"function":"wait","class":"Symfony\\Component\\Process\\Process","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/process/Process.php","line":268,"function":"run","class":"Symfony\\Component\\Process\\Process","type":"->"},{"file":"/var/www/nextcloud/apps/ncdownloader/lib/Aria2/Aria2.php","line":375,"function":"mustRun","class":"Symfony\\Component\\Process\\Process","type":"->"},{"file":"/var/www/nextcloud/apps/ncdownloader/lib/Controller/MainController.php","line":94,"function":"start","class":"OCA\\NCDownloader\\Aria2\\Aria2","type":"->"},{"file":"/var/www/nextcloud/apps/ncdownloader/lib/Controller/MainController.php","line":59,"function":"buildParams","class":"OCA\\NCDownloader\\Controller\\MainController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"Index","class":"OCA\\NCDownloader\\Controller\\MainController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1058,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/symfony/process/Process.php","Line":441,"CustomMessage":"--"}}

**Comment by IkariDevGIT** [comment]
i have the same problem, please fix @shiningw

**Comment by amiroof** [comment]
> i have the same problem, please fix @shiningw

It seems to only happen on Ubuntu 22. It working now that I moved to Ubuntu 20.

**Comment by bilibili540** [comment]
I think aria2 must be started before NCdownload can be opened.
