### ISSUE TITLE
nextcloud 30 issue with yt-dlp

### ISSUE THREAD

**Issue by zqpvr** [shiningw/ncdownloader#166]
```
WARNING: Writing cache to '/var/www/.cache/yt-dlp/youtube-nsig/34059770.json' failed: Traceback (most recent call last):
File "/var/www/nextcloud/apps/ncdownloader/lib/Ytdl/../../bin/yt-dlp/yt_dlp/cache.py", line 41, in store
os.makedirs(os.path.dirname(fn), exist_ok=True)
File "", line 215, in makedirs
File "", line 215, in makedirs
File "", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/var/www/.cache'

WARNING: Writing cache to '/var/www/.cache/yt-dlp/youtube-nsig/34059770.json' failed: Traceback (most recent call last):
File "/var/www/nextcloud/apps/ncdownloader/lib/Ytdl/../../bin/yt-dlp/yt_dlp/cache.py", line 41, in store
os.makedirs(os.path.dirname(fn), exist_ok=True)
File "", line 215, in makedirs
File "", line 215, in makedirs
File "", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/var/www/.cache'

ERROR: unable to create directory [Errno 17] File exists: '/tmp/oc_tmp_ovUTYh'
✖
```
I get this error when trying to download youtube videos with latest yt-dlp on ubuntu 24.04 on nextcloud 30, even with torrents but it gets further but when it downloads something I check /Downloads and there is nothing in there.

**Comment by amir-fo** [comment]
There are to ways to fix this by my knowledge. 
1- creat the directory .cache and give permission to you webserver

2- if you dont need caching add "$this->addOption('--no-cache-dir');" without"" to line 146 of ytdl.php located at /path/to/your/nextcloud/apps/ncdownloader/lib/ytdlp

2nd option has fixed the error for me.

**Comment by darkpisto** [comment]
New life of the NCDDownloader project on the Vapor project here:
https://apps.nextcloud.com/apps/vapor
And here:
https://github.com/wolfravenous/vapor/issues
